version: "3"
services:
    Cloud_95596:
        build: ./mysql
        image: my_db
        environment:
            MYSQL_USER: PTlusty
            MYSQL_PASSWORD: pass123
        networks:
            - Bridge-Zadanie-1
        ports:
            - 3306:3306

    Java_App:
        build: .
        image: java_img
        networks:
            - Bridge-Zadanie-1
        depends_on:
            - Cloud_95596

networks:
        Bridge-Zadanie-1:

