version: "3"
services:
    Cloud_95596:
        build: ./mysql
        image: my_db
        environment:
            MYSQL_USER: PTlusty
            MYSQL_PASSWORD: pass123
        networks:
            Bridge-Zadanie-1:
                ipv4_address: 10.0.10.3
        ports:
            - 3306:3306
        command: ["./wait-for-it.sh", "mysql:3306", "--", "mysqld"]

    Java_App:
        build: .
        image: java_img
        networks:
            - Bridge-Zadanie-1
        depends_on:
            - Cloud_95596
        command: ["./wait-for-it.sh", "Cloud_95596:3306", "--", "java", "-cp", "mysql-connector-j-8.0.33.jar:.","Main"]

networks:
        Bridge-Zadanie-1:
            driver: bridge
            ipam:
                config:
                    - subnet: 10.0.10.0/24
